import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Demo() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Demo | Quotom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='py-8 text-2xl'>Quotom</h1>

      <button className='bg-indigo-600 p-2 rounded-lg'>
        <a href="/">
          Back
        </a>
      </button>
      
      <div className="container mx-auto bg-gray-700  h-10 w-1/2 rounded-md text-center">
        <div className="py-2 px-4 text-center">
          <h1 className='text-center'>Demo</h1>
        </div>
      </div>

      <div className='container mx-auto'>
        <p className='my-5 text-center'>(*All mock numbers, not real... yet)</p>
        <p className='my-5'>Enter Information</p>
        

        <form className='grid mx-5 my-2'>
          <h2 className='text-center'>Card #1</h2>
          <label>Card number:</label>
          <input type='text' placeholder='Enter...' className='bg-gray-200 rounded-sm p-2 m-2 text-black'></input>
          <label>Expiration:</label>
          <input type='text' placeholder='Enter...' className='bg-gray-200 rounded-sm p-2 m-2 text-black'></input>
        </form>


        <form className='grid mx-5'>
          <h2 className='text-center my-5'>Card #2</h2>
          <label>Card number:</label>
          <input type='text' placeholder='Enter...' className='bg-gray-200 rounded-sm p-2 m-2 text-black'></input>
          <label>Expiration:</label>
          <input type='text' placeholder='Enter...' className='bg-gray-200 rounded-sm p-2 m-2 text-black'></input>
        </form>

        <div className='mx-auto py-8 px-4 text-center'>
          <button className='bg-gray-700 w-1/2 p-2 rounded-lg m-5'>Submit</button>
        </div>
      </div>
      

    </div>
  )
}