import Create from '../components/CardForms'
import Nav from '../components/Nav'
import Head from 'next/head'

export default function Demo() {

  return (
    <div className=''>
      <Head>
        <title>Demo | Quotom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav/>
      <Create/>
    </div>

  )
}