import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Faq from "../components/faq"
import Team from "../components/team"
import Hero from "../components/hero"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home | Quotom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='py-8 text-2xl'>Quotom</h1>
      
      <Hero></Hero>
      <Faq></Faq>
      <Team></Team>

    </div>
  )
}
