import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

function getCards () {
  return JSON.parse(localStorage.getItem("stickynotes-notes") || "[]");
}

function saveCards () {
  localStorage.setItem("stickynotes-notes", JSON.stringify(notes));
}

function createCardElement(id, content) {
  const element = document.createElement("textarea");
}

function addCard () {

}

function updateCard(id, newContent) {

}

function deleteNote(id, element) {

}

export default function Demo() {

  const [cards, setCards] = useState([
    { number: '123456789', expiration: '1101', cvc: '456'},
  ]);

  return (
    <div>
      <Head>
        <title>Demo | Quotom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='py-8 text-2xl'>Quotom</h1>

      <button className='bg-indigo-600 p-2 rounded-lg'>
        <a href="/">
          Back
        </a>
      </button>

      {cards.map((card) => (
        <div className='card-preview' key={}></div>
      ))}
    
    </div>
  )
}



<div>
{cards.map((card) => (
  <div className='m-20 p-5 h-48 w-84 bg-gray-700 rounded-lg' key={card.cvc}>
    <h1 className='p-2 my-2'> Card {card.id}</h1>
    <h2 className='mx-4'> Card number: { card.number } </h2>
    <p className='mx-4'> Expiration: { card.expiration } </p>
    <p className='mx-4'> CVC: { card.cvc } </p>
  </div>
))}
</div>